export const students=[
    {'user_id':1,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':2,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':3,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':4,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':5,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':6,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':7,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':8,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':9,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':10,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
    {'user_id':11,'name':'abcd','email':'abc@gmail.com','dob':'dd-mm-yyyy','address':'#random address','gender':'female','major':'Stream1','university':'University 1'},
]
export const products=[
    {'id':1, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':2, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':3, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':4, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':5, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':6, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':7, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':8, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':9, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
    {'id':10, 'name':'Product1','description':'This is the description of my product','price':1000,'category':'Category1','quantity':100},
]